project:
  type: website

website: 
  title: "2025_DAIE_ICA_1"
  navbar: 
    left:
      - text: "SQL" 
        href: SQL.qmd
      - text: "Linear Regression"
        href: linearregression.qmd
      - text: "Technology Exploration"
        href: technologyexploration.qmd


